name: Kotlin CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Gradle
      working-directory: backend
      run: ./gradlew build
    - name: Run tests
      id: tests
      working-directory: backend
      run: |
        ./gradlew test > test-results.txt

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/build/reports/tests/test

    - name: Notify Success
      if: ${{ steps.tests.outcome == 'success' }}
      run: |
        LAST_LINES=$(tail -n 10 backend/test-results.txt)
        MESSAGE="All tests have passed successfully. The commit can be merged.
        $LAST_LINES"
        gh issue create --title "Tests passed" --body "$MESSAGE" --label "CI/CD" --assignee ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
    - name: Notify Failure  
      if: ${{ steps.tests.outcome == 'failure' }}
      run: |
        LAST_LINES=$(tail -n 10 backend/test-results.txt)
        MESSAGE="Some tests have failed. Please fix the issues before merging the commit.
        $LAST_LINES"
        gh issue create --title "Tests failed" --body "$MESSAGE" --label "CI/CD" --assignee ${{ github.actor }} 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

