name: Trigger Main Repo Sync
on:
  push:
    branches:
      - main
env:
  SUBMODULE_NAME: "Tickify-backend"

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Update submodules to the latest commit
        run: git submodule update --remote --merge
        
      - name: Trigger main repository update
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Tik-it/Tikit-backend/dispatches \
          -d "{
          \"event_type\": \"submodule-main-updated\",
          \"client_payload\": {
          \"submodule\": \"$SUBMODULE_NAME\",
          \"commit\": \"$GITHUB_SHA\"
          }
          }"
